Add support for Bzlmod (#242)
* Add support for Bzlmod

Requires fixing a case of a non-hermetic Python import in
`dict_validation_test` that breaks with Python 3.11, with which Bazel
uses `PYTHONSAFEPATH` by default.

A follow-up PR will provide the publishing setup for releases to the
Bazel Central Registry (BCR).

* Disable layering_check for OSS-Fuzz

OSS-Fuzz builds fail with:
```
ERROR: /root/.cache/bazel/_bazel_root/17db7bb59affe64429348778697da03a/external/abseil-cpp~20230802.1/absl/strings/BUILD.bazel:591:11: Compiling absl/strings/internal/cordz_functions.cc failed: undeclared inclusion(s) in rule '@@abseil-cpp~20230802.1//absl/strings:cordz_functions':
this rule is missing dependency declarations for the following files included by 'absl/strings/internal/cordz_functions.cc':
  'bazel-out/k8-opt-ST-b76ee6246659/bin/external/abseil-cpp~20230802.1/absl/base/atomic_hook.cppmap'
  'bazel-out/k8-opt-ST-b76ee6246659/bin/external/abseil-cpp~20230802.1/absl/base/errno_saver.cppmap'
  'bazel-out/k8-opt-ST-b76ee6246659/bin/external/abseil-cpp~20230802.1/absl/base/log_severity.cppmap'
```

These files are emitted by Bazel when using the `layering_check`
feature. This looks like a bug or breaking change in clang.

* Revert "Disable layering_check for OSS-Fuzz"

This reverts commit 60a831d46ce6de6a5eed6bf63ae4f0f5087864ac.

* Address review comments

* Update abseil and use a custom repo_name

* Add subproject to .bazelignore

* Use `Label` in macros

* Update Bazel to 7.0.2 and ignore WORKSPACE repos in example repo

* Add _repo_mapping file if supported

* Apply repo mapping to local_jdk exclusion

* Fix failure if there are no runfiles

* Make `local_jdk` visible